### ISSUE TITLE
Spectroscopy maps

### ISSUE THREAD

**Issue by zrbyte** [rescipy-project/spym#7]
I really love this implementation of the RHK data, using xarray. However, as opposed to the older implementation (RHK-SM4), spym doesn't load spectroscopy data from dI/dV maps or file where the spectra are measured along a line. I can't seem to figure out why. Here are examples of the files I've been trying: https://drive.google.com/drive/folders/13r9UzeyTe_2WJrbM6yex8OiA0oJ1Z-Oc?usp=share_link
I would love to use spym as a base to build spectroscopy processing tools, but I can't seem to figure out why it doesn't load the spec data.

**Comment by mpanighel** [comment]
Dear @zrbyte thank you for the feedback.
The issue should be now solved with version 0.8.0 (commits https://github.com/rescipy-project/spym/commit/4756234ebb5afcbd4c75040ce9936d3b4eaa6402 and https://github.com/rescipy-project/spym/commit/a8107cca0c51513c3961df8ebce09a585407c21a).

Please update the spym package and let me know if it is working for you. Also, please check if all data is correctly plotted by spym as some channels in the example files you linked contains just NaNs.

**Comment by zrbyte** [comment]
Hi,

The data does not contain NaNs, page 6 and page 7 contain the Lock-In (LIA) and Current channels of the spectroscopy. Physically, the data is structured as following: 4x4 spatial grid, with two spectra (forward and backward sweep of the voltage) in each point. Thus, 32 spectra in all. The spectra themselves have 241 data points each. When plotting this 32x241 array from page 6 it should look like this:
![image](https://user-images.githubusercontent.com/33519217/221186671-7cdf4649-7566-4148-8630-f0be3b1e80eb.png)

Now, using version 0.8 of spym page 6 and 7 load as NaN. However, using just the `rhksm4` loader from spym the data loads, but the axes are switched. There might be a problem in the order in which the spectroscopy data is loaded, since rearranging the array gets the right order. See this [notebook](https://drive.google.com/file/d/1YXlwBphD-14t4yxWinkSSw97XtSiynZY/view?usp=share_link) (pdf version [here](https://drive.google.com/file/d/1vQKMKPFsHIZbo9KK2KUqoG15WuRYfvAm/view?usp=share_link)).

**Comment by mpanighel** [comment]
Hi,

I see. Then there are at least two issue here.

`spym.load()` actually points to `spym.io.rhksm4.to_dataset()` (to generate the xarray) which in turn uses `spym.io.rhksm4.load() ` to parse data from the sm4 file.

So there is an axis switching in `rhksm4.load` and some kind of wrong data conversion in `rhksm4.to_dataset`.

I will have a look into it.

**Comment by mpanighel** [comment]
> So there is an axis switching in `rhksm4.load` and some kind of wrong data conversion in `rhksm4.to_dataset`.

@zrbyte This is now fixed with commit https://github.com/rescipy-project/spym/commit/b5dd99eaf7a298ea04df34eb750f7dfa7ba8d282 included in v0.9.0.

Note that some waterfall plotting options for spectra have also been included.

**Comment by mpanighel** [comment]
I am closing the issue. If the problem should persist, please reopen it.
